### ISSUE TITLE
数据量很大的时候会卡主吗

### ISSUE THREAD

**Issue by hklinux2010** [hanzhongzi/zabbix_pratition_tables#1]
zabbix采用分布式搭建 大概每秒的写入数据量为140000左右，直接做表分区是不是会把 mysql 卡爆

**Comment by hanzhongzi** [comment]
> zabbix采用分布式搭建 大概每秒的写入数据量为140000左右，直接做表分区是不是会把 mysql 卡爆

确实会卡爆的 ![image](https://github.com/hanzhongzi/zabbix_pratition_tables/assets/38389787/84cdb65c-a9b5-44df-b3ae-ada6af413023) 我在第二部分如何使用的注意中没有标注加粗！可能您没有注意到，我稍后改一下。这个操作建议是在“上图注意部分中说的在最初的时候就这样搞”。 如果您已经是用了很久成型的zabbix架构了，建议新建数据库按照如上操作，然后让新集群的主成为旧集群的从库（或者使用数据迁移工具） 等待数据追平后做一次迁移。

**Comment by hanzhongzi** [comment]
hi~ 我已添加说明, 请问还有什么问题。 如果需要协助或者更加详细的建议，请到数据库中执行一下这个命令给我看看。
```sql
 select table_name, (data_length/1024/1024) as data_mb , (index_length/1024/1024)   as index_mb, ((data_length+index_length)/1024/1024) as all_mb, table_rows   from information_schema.tables where table_schema = '你的数据库名称' order by all_mb;  

 select table_name, (data_length/1024/1024) as data_mb , (index_length/1024/1024)   as index_mb, ((data_length+index_length)/1024/1024) as all_mb, table_rows   from information_schema.tables where table_schema = '你的数据库名称' and (table_name like 'history%' or table_name like 'trends%')) order by all_mb;  
```

**Comment by hklinux2010** [comment]
没有了，谢谢
